#  ___    __     __________
#  __ |  / /________  /_  /_
#  __ | / /_  __ \_  /_  __/
#  __ |/ / / /_/ /  / / /_
#  _____/  \____//_/  \__/
#
server-port: 5000
  # The port you want you server to run on
pool-size: 4
  # Size to use for the client handler pool
  # (If you don't understand this, you don't need to change it)
special-pages:
  index: "/index.html"
  404: "/404.html"
